#!/usr/bin/env node
// Generates lib/pinyin_data.js from the pinyin-pro npm package.
// Run with: node build_scripts/generate_pinyin_data.mjs
// Requires: npm install -g pinyin-pro  OR  npm install pinyin-pro in a local dir.
//
// The generated file maps CJK Unified Ideographs (U+4E00..U+9FFF) to their
// Mandarin pinyin syllables (without tone marks) using a compact base64-encoded
// Uint16Array.

import { createRequire } from "module";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Support both: pinyin-pro installed globally, or installed in a local temp dir passed
// as the first argument, e.g.:
//   mkdir /tmp/pg && cd /tmp/pg && npm init -y && npm install pinyin-pro
//   node build_scripts/generate_pinyin_data.mjs /tmp/pg
const localDir = process.argv[2];
const require = createRequire(localDir ? join(localDir, "dummy.js") : import.meta.url);
const { pinyin } = require(localDir ? join(localDir, "node_modules/pinyin-pro") : "pinyin-pro");

const CJK_START = 0x4E00;
const CJK_END = 0x9FFF;

const syllablesSet = new Set();
const charPinyinMap = {};

for (let code = CJK_START; code <= CJK_END; code++) {
  const char = String.fromCharCode(code);
  const p = pinyin(char, { toneType: "none", separator: "" }).trim();
  if (p && p !== char) {
    charPinyinMap[code] = p;
    syllablesSet.add(p);
  }
}

const syllables = Array.from(syllablesSet).sort();
const syllableToIndex = Object.fromEntries(syllables.map((s, i) => [s, i]));

// Build a Uint16Array: index i → syllable index + 1 for CJK_START + i (0 = no data).
const length = CJK_END - CJK_START + 1;
const indices = new Uint16Array(length);
for (let code = CJK_START; code <= CJK_END; code++) {
  const p = charPinyinMap[code];
  if (p != null) indices[code - CJK_START] = syllableToIndex[p] + 1;
}

const base64 = Buffer.from(indices.buffer).toString("base64");
const charCount = Object.keys(charPinyinMap).length;

const output = `\
// Auto-generated by build_scripts/generate_pinyin_data.mjs - do not edit manually.
// CJK Unified Ideographs (U+4E00..U+9FFF) → pinyin syllable index.
// ${charCount} characters mapped, ${syllables.length} unique syllables.

// All unique pinyin syllables (no tones), sorted alphabetically.
export const syllables = ${JSON.stringify(syllables)};

// Base64-encoded Uint16Array. Index i corresponds to U+4E00+i.
// Value 0 = no data; value n = syllables[n-1].
export const indicesBase64 = "${base64}";
`;

const outPath = join(__dirname, "../lib/pinyin_data.js");
writeFileSync(outPath, output);
console.log(`Generated ${outPath}`);
console.log(`Characters: ${charCount}, Syllables: ${syllables.length}`);
